org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
org.gradle.daemon=false
kotlin.daemon.enabled=false
kotlin.daemon.jvmargs=-Xmx1536M
kotlin.incremental.useClasspathSnapshot=false
kotlin.incremental=false